### ISSUE TITLE
Doubled patch files

### ISSUE THREAD

**Issue by BureauJaeger** [linuxgurugamer/SXTContinued#12]
There's a WIP folder inside the ModCompatibility directory that seems to have some unnecessary or conflicting files. Probably leftovers?
https://github.com/linuxgurugamer/SXTContinued/tree/master/GameData/SXT/Patches/ModCompatibility/WIP
The two Modular Fuel Tanks patches are identical, and one of the two Tweakscale patches is unneeded but which one is more current, the one in WIP or the one in ModCompatibility? There's two nearly identical files for Firespitter too.

**Comment by linuxgurugamer** [comment]
Will look into it

**Comment by linuxgurugamer** [comment]
Was fixed in last release, thanks
