### ISSUE TITLE
0.625m fairing too heavy and expensive

### ISSUE THREAD

**Issue by andrewcchen** [linuxgurugamer/SXTContinued#17]
- The unit area mass and unit area cost are both much larger than even the 3.75m fairing, when they should be smaller than the 1.25m fairing.
- Similarly the cost and entry cost are too expensive

Also, the description should be fixed to not say AE-FF3.

The 5m fairing unit area mass also seems a bit too heavy.

Tags (1.2 update?) should be added (probably just copy from stock fairing) for the 0.625m and 5m fairings.

It would also be nice to have the truss structure introduced in 1.2 added for the two fairings.

**Comment by linuxgurugamer** [comment]
I assume the PR you submitted took care of all of this?

**Comment by andrewcchen** [comment]
Yes
