### ISSUE TITLE
Clyde internal model.mu missing (was removed unintentionally)

### ISSUE THREAD

**Issue by khr15714n** [linuxgurugamer/SXTContinued#29]
GameData/SXT/Spaces/Clyde/model.mu

see http://forum.kerbalspaceprogram.com/index.php?/topic/151129-12-sxt-continued/&page=9#comment-3016260
> New release, 0.3.11:
> Update Clyde internals with fixed textures, converted remaining png to dds, thanks to @Drew Kerman

I've tried to use the old, zipped model.mu and it seems to work again.
KSP.log seems also to be happy again.

**Comment by linuxgurugamer** [comment]
What's the problem?  No logs, no error messages?

**Comment by khr15714n** [comment]
released:
[LOG 23:37:37.068] PartLoader: Compiling Internal Space 'SXT/Spaces/BonnyInternals/internal/BonnyInternals'
[LOG 23:37:37.074] PartLoader: Compiling Internal Space 'SXT/Spaces/Clyde/internal/clydeInternal'
[ERR 23:37:37.076] PartCompiler: Cannot clone model 'SXT/Spaces/Clyde/model' as model does not exist

[ERR 23:37:37.076] PartCompiler: Model was not compiled correctly

[LOG 23:37:37.077] LoadInternalPart 'SXT/Spaces/Clyde/internal/clydeInternal' FAILED: Cannot find model

---------------
adding model.mu (OldImages.zip):
[LOG 23:42:05.268] PartLoader: Compiling Internal Space 'SXT/Spaces/BonnyInternals/internal/BonnyInternals'
[LOG 23:42:05.274] PartLoader: Compiling Internal Space 'SXT/Spaces/Clyde/internal/clydeInternal'
[LOG 23:42:05.283] PartLoader: Compiling Internal Space 'SXT/Spaces/Duna/internal/SXT5mhabIVA'

**Comment by linuxgurugamer** [comment]
Being fixed in the next release
