### ISSUE TITLE
Mini Goo texture

### ISSUE THREAD

**Issue by TheGreatRevanchist** [linuxgurugamer/SXTContinued#31]
You MIGHT want to look at the mini-goo texture... Its a bit broken and you'll see why if its not just me

**Comment by linuxgurugamer** [comment]
Could you post a picture showing me the issue?
Thanks

**Comment by Ruedii** [comment]
It's all black.  I'll snap a picture next time I play KSP.

There is an error on game load relating to it as well.

Several other parts are getting minor errors on their referenced textures being missing on load as well, but none of them are textures you would notice.  I'll probably pastebin the log, although if it's OK with you, I won't bother uninstalling other mods.  As far as I can tell they are playing nice with SXT.  (Contract Configurator is periodically having some other minor problems with seemingly random NREs, but they aren't at all part related.)

**Comment by LeLeon** [comment]
still present, part is black, no use of part.cfg .dds links.

**Comment by linuxgurugamer** [comment]
Looks like I fixed this last year
