### ISSUE TITLE
Bad AtmCurves

### ISSUE THREAD

**Issue by voicey99** [linuxgurugamer/SXTContinued#35]
The RK-170 "Tsar-Pushka", LV-NX3 "NERVA", LV-405 "Vanguard" and LV-10-37 "Rearguard" engines' AtmosphereCurve keys do not extend to atmospheres denser than 1atm, meaning they are unaffected by thicker atmospheres like Eve's and gain a major advantage by not being affected by the thick atmospheres.

Similarly, the BBCV-4350 "Candle Wax" SRB's curve is also poorly configured, with the I^SP dropping substantially *below* zero and causing it to display significant negative thrust between 1.6 and 5.4atm. It does not appear to apply this thrust, however.

**Comment by linuxgurugamer** [comment]
Ok, can you provide better ones?

**Comment by voicey99** [comment]
Do you have any guidance as to when they should hit zero? Otherwise I'll just write in what I *think* it should be.

**Comment by linuxgurugamer** [comment]
None at all.  up to you right now, but be prepared for comments on the forums

**Comment by voicey99** [comment]
I'm making some changes to other parts while I'm at it, and some of the parts have this tag:

	// ----- DO NOT EDIT BELOW THIS POINT ------
	// --- I'll do what I want thank you very much ---

Does that mean nobody is allowed to do anything with that section at all?

**Comment by voicey99** [comment]
(Oops, misclick)

**Comment by linuxgurugamer** [comment]
No, that was from the original author.  You can ignore them
