### ISSUE TITLE
no sound plays when engines turn on

### ISSUE THREAD

**Issue by CrazyPuffleGamer** [linuxgurugamer/SXTContinued#49]
I tried the mod on ksp and the propeller sound didn't play.

**Comment by CrazyPuffleGamer** [comment]
@linuxgurugamer

**Comment by CrazyPuffleGamer** [comment]
@linuxgurugamer

**Comment by CrazyPuffleGamer** [comment]
@linuxgurugamer

**Comment by linuxgurugamer** [comment]
More info is needed, such as, which version of KSP, what other mods do you have installed, etc.  Also, a log file would be helpful

**Comment by CrazyPuffleGamer** [comment]
Well, I also have BDArmory and Tweakscale, and I'm pretty sure I have
version 1.3.

**Comment by CrazyPuffleGamer** [comment]
Well, I also have BDArmory and Tweakscale, and I'm pretty sure I have version 1.3.

**Comment by CrazyPuffleGamer** [comment]
I keep on forgetting that close issue is not delete comment

**Comment by CrazyPuffleGamer** [comment]
there is also no animation for the propellers. It just moves forward.

**Comment by linuxgurugamer** [comment]
I need a log file, I also need to know how you installed it.
Really sounds like you missed a dependency

**Comment by CrazyPuffleGamer** [comment]
i have no idea what a log file is, and I downloaded it from mega

**Comment by CrazyPuffleGamer** [comment]
And just FYI at 4 I have to leave and I can't contact you for a week

**Comment by linuxgurugamer** [comment]
Love that pressure :-(

I have no idea what "mega" has online.

You need to go to spacedock.info to download it (or from the releases directory here).
And read the forum post here:
https://forum.kerbalspaceprogram.com/index.php?/topic/151129-131-sxt-continued/
for specifics on what else is needed

**Comment by CrazyPuffleGamer** [comment]
on the forum I saw no specs on what's needed. It's just a description on what the mod is.

**Comment by CrazyPuffleGamer** [comment]
I downloaded KSP from Mega.co.nz

**Comment by linuxgurugamer** [comment]
I have no idea what's on Mega.co.nz, nor am I going to spend any time on it.  It is not an official distribution server, and most likely has old code, and doesn't include the dependencies.
Regarding what's on the, there is a line in red, on the first page, I'm copying it below:

"Requires the Firespitter dll and the Firespitter Resources folder to be installed"

Closing this since it's obviously just missing firespitter

**Comment by linuxgurugamer** [comment]
If you downloaded KSP from Mega, then you are using an illegal copy of the game,  and I will not have anything else to do with you.
sorry
