### ISSUE TITLE
Osaul Cargo Bay not working

### ISSUE THREAD

**Issue by LeLeon** [linuxgurugamer/SXTContinued#51]
\SXT\Parts\Aviation\Hull\Osaul\Hull.cfg

title = M-Hull 3.75m 'Osaul' Cargo Bay

Door will not open in VAB/ flight scene.

"
MODULE
	{
		name = ModuleCargoBay  // (check)
		//DeployModuleIndex = 0 //--Might throw an error // Threw an error "not an IScalarModule"
		closedPosition = 0 // 1
		lookupRadius = 5.0 // 2.7
		nodeOuterForeID = top
		nodeOuterAftID = bottom
		//nodeInnerForeID = top2
		//nodeInnerAftID = bottom2
	}
"

**Comment by Schnobs** [comment]
AFAIK the Osaul hull is just a tube, it has no doors. In order to get anything in or out, you're supposed to use it together with the Osaul Cockpit and folding ramp.
