### ISSUE TITLE
Module  Manager Error FAR related

### ISSUE THREAD

**Issue by LeLeon** [linuxgurugamer/SXTContinued#52]
related to: SXT\Patches\ModCompatibility\FAR\FAR_Engines.cfg

module manager give warning for 8 errors during game start

[ERR 15:32:42.676] [ModuleManager] Error - more than one pass specifier on a node: SXT/Patches/ModCompatibility/FAR/FAR_Engines/@PART[SXTPWR2800|SXTKO211Dprop|SXTKO211prop|SXTTinyprop|SXTeFan|SXTMerlin66prop|SXTNK12M|SXTPWPT6]:FOR[SXT]:AFTER[SXT]

[ERR 15:32:42.676] [ModuleManager] Error - more than one pass specifier on a node: SXT/Patches/ModCompatibility/FAR/FAR_Engines/@PART[SXTPWR2800]:FOR[SXT]:AFTER[SXT]

[ERR 15:32:42.676] [ModuleManager] Error - more than one pass specifier on a node: SXT/Patches/ModCompatibility/FAR/FAR_Engines/@PART[SXTKO211Dprop]:FOR[SXT]:AFTER[SXT]

[ERR 15:32:42.677] [ModuleManager] Error - more than one pass specifier on a node: SXT/Patches/ModCompatibility/FAR/FAR_Engines/@PART[SXTKO211prop]:FOR[SXT]:AFTER[SXT]

[ERR 15:32:42.677] [ModuleManager] Error - more than one pass specifier on a node: SXT/Patches/ModCompatibility/FAR/FAR_Engines/@PART[SXTTinyprop]:FOR[SXT]:AFTER[SXT]

[ERR 15:32:42.677] [ModuleManager] Error - more than one pass specifier on a node: SXT/Patches/ModCompatibility/FAR/FAR_Engines/@PART[SXTMerlin66prop]:FOR[SXT]:AFTER[SXT]

[ERR 15:32:42.677] [ModuleManager] Error - more than one pass specifier on a node: SXT/Patches/ModCompatibility/FAR/FAR_Engines/@PART[SXTNK12M]:FOR[SXT]:AFTER[SXT]

[ERR 15:32:42.677] [ModuleManager] Error - more than one pass specifier on a node: SXT/Patches/ModCompatibility/FAR/FAR_Engines/@PART[SXTPWPT6]:FOR[SXT]:AFTER[SXT]

**Comment by linuxgurugamer** [comment]
I know I fixed that, I must have undone the commit.
Will get it fixed, thanks

**Comment by linuxgurugamer** [comment]
Please check what version you are using, this was fixed a long time ago.
I just checked the files on Github and in the download
