### ISSUE TITLE
version info for 0.3.23.1

### ISSUE THREAD

**Issue by ericfriesen** [linuxgurugamer/SXTContinued#54]
Downloading v 0.3.23.1
SXTContinued.version contains version info for 0.3.23.5 and is marked for 1.4.
Is it really 0.3.23.5 that's downloaded or is the version file wrong? Is this version fully compatible with 1.3?
Thank you.

**Comment by linuxgurugamer** [comment]
It's fine.  The file got deleted by accident, I had to recreate it.  I verified that the DLLs included were for 1.3.1, so I'd suggest just deleting the .version file to avoid any annoying messages
