### ISSUE TITLE
Loading stuck on SXTeFan

### ISSUE THREAD

**Issue by m4ti140** [linuxgurugamer/SXTContinued#55]
**KSP:** 1.4.3 64bit dx9

**Problem:** Loading gets stuck at SXT/Parts/Aviation/Engine/propEngines/eFan/SXTeFan. No crash occurs, the process isn't listed as not responding, the game just sits there until the process is killed.
EDIT: The game loads correctly without this part

**Mods:** [mods.txt](https://github.com/linuxgurugamer/SXTContinued/files/1969206/mods.txt)

**Reproduction steps:** Launch the game

**Log:** [output_log.txt](https://github.com/linuxgurugamer/SXTContinued/files/1969204/output_log.txt)

**Comment by theonegalen** [comment]
It's the firespitter resources folder. It is mentioned as a dependency in the KSP forum post.

https://forum.kerbalspaceprogram.com/index.php?/topic/151129-141-sxt-continued/&

**Comment by linuxgurugamer** [comment]
Please read the instructions of mods before reporting issues
