### ISSUE TITLE
Probodobodyne QUBC "Warbler - fake solar panels

### ISSUE THREAD

**Issue by yalov** [linuxgurugamer/SXTContinued#57]
Way to reproduce:
Put Small Reaction Wheel (0.625m) on top of the Probe and HyperEdit to a orbit.

Expected Behavior:
Always getting some energy from the Sun, 
Never blocked by Small Reaction Wheel

Real Behavior:
`Sun Exposure = 0` and `Energy Flow = 0` (6 times), 
Blocked by Small Reaction Wheel (2 times) 

![](https://i.imgur.com/RzBYqWf.png)

------------------

There is hack in the config, all covered solar panels are one `ModuleDeployableSolarPanel`, and as pictures show, it doesn't really work.

**Comment by linuxgurugamer** [comment]
This is a quirk of the way KSP works and the way this part was made.  It's using the same model for each of the 6 solar panels, which means that each model has the same names internally for the transforms, and there is no way, short of making 6 different models, of referencing each.
and I can't just take the Squad model and modify it, unfortunately

**Comment by linuxgurugamer** [comment]
I will see if someone can make me 8 identical solar panels to use in this

**Comment by linuxgurugamer** [comment]
Will be fixed in the upcoming release
