### ISSUE TITLE
1.5.x functionality for Meadowlark pod

### ISSUE THREAD

**Issue by jh4c** [linuxgurugamer/SXTContinued#59]
The Meadowlark Observation Pod requires "CrewCapacity = 2" to allow kerbals to be assigned to the jumpseats while in the VAB/SPH.

The Crew Report science experiment is not available when using this part as it "requires the {part} to be manned." I'm unaware of any way around this requirement when using external crew seats. There is a science storage container fitted to the pod which is therefore redundant, as there is no way for the crew to access it.

No other issues have been noted when using this pack in 1.5.x.

**Comment by linuxgurugamer** [comment]
Thank you, I've fixed this locally, and will be in the next release
