### ISSUE TITLE
Needs work for 1.5.x release

### ISSUE THREAD

**Issue by Ruedii** [linuxgurugamer/SXTContinued#60]
The prerequisites (Firespitter and Retractable Lifting Surfaces) now support 1.5.x and the mod now works fine.   

The AVC version file just needs updating now for full 1.5.x support.

Not a high priority update, but not exactly a lot of work to do.

**Comment by linuxgurugamer** [comment]
There is other stuff going on, please be patient

**Comment by linuxgurugamer** [comment]
Also, while there may be a Firespitter DLL on Github, it  hasn't been released yet.

**Comment by Ruedii** [comment]
Yeah, I noticed, it's not an updated version, the old version just still works.  It probably could benefit from a recompile just to be safe, but I don't even know if the dev kit was really changed in any ways that would affect it at all.

Any specific issues with any mods I could help with?
I have tried many of the parts in this mod and haven't run into any issues with 1.5.1.  

If you know specific issues with this mod, such as wheel behaviors that need readjustment, I can help.   I tend to fine-tune my wheels when I make any wheeled vehicle, so I might not notice the bad behavior. 

If you have other mods that need work, I can help there too.   

Specific Mods (not yet updated) I've used and are thus familiar with the standard behavior on that you maintain are:
Take Command Continued
Quiztech Aerospace

Ones some of your mods are dependent on or recommend
Firespitter Core
Contract Configurer

Several more need AVC version file updates, but honestly that is such a petty change that it can be given extremely low priority. Getting the version files for CKAN updated should be higher priority.


(Man I thought more needed updating, seems they don't.)

**Comment by Ruedii** [comment]
I found one bug, BTW, I don't know if it's related to the KSP update.  If you leave the "Buzzard" cockpit through the side exit in space, it will send your kerbal spinning off at 200ms or so due to a minor collider bug.    At least deserves listing under known bugs.  I'll try out some of the wheels.

I'm going to change this bug's title to indicate needs work for 1.5.1 release.

**Comment by linuxgurugamer** [comment]
Not too much I can do about that, but may have someone who can help

**Comment by linuxgurugamer** [comment]
FYI, the Take Command Continued is deprecated, since it is now stock
and there are changes to firewspitter, which is why I'm waiting for it

**Comment by Ruedii** [comment]
They made some changes irregardless. 

I also noticed a few more texture bugs.  I should probably lump them in with the Robin one.  However, these ones might be harder to fix, considering there might not be an equivalent part. 

BTW, do you know which mod had the empty truck cabs for mounting command seats.   I can't remember.  Was it KSPX?
