### ISSUE TITLE
Multiple engines' models aren't centered

### ISSUE THREAD

**Issue by PatPL** [linuxgurugamer/SXTContinued#68]
This doesn't affect the engine in any way though, because thrustTransform, and attachment nodes is in correct place. This is a purely cosmetic issue.

![](https://imgur.com/xll9GFO.png)

As you can see, the nozzle isn't aligned with centered cyllinder

EDIT:
K170/model25.mu (RE-M1 "Commodore") has a similar problem, but on the base of the engine. There is some offset on the bell too, but it's too small to be noticeable.
![](https://imgur.com/PQ1pVD5.gif)

EDIT2:
J-2's model might be the worst offender in this mod. The 'gimbal' object, and therefore 'thrustTransform' are off center.
![](https://imgur.com/pwHs1Ze.png)

**Comment by linuxgurugamer** [comment]
Any chance you could provide updated models?

**Comment by PatPL** [comment]
Done, Here's the PR: https://github.com/linuxgurugamer/SXTContinued/pull/69

I don't have any KSP install on hand rn, so I'd appreciate it if you checked whether I didn't break anything before next release.
