### ISSUE TITLE
Patches are applied to Stock Mun Lander instead of SXT Mun Lander

### ISSUE THREAD

**Issue by ncanceill** [linuxgurugamer/SXTContinued#70]
**Description**
Some patches are applied to the stock `MEMLander` instead of the `MEMLanderSXT`.

**Root cause**
When the Munar Excursion Module was renamed from `MEMLander` to `MEMLanderSXT` in 5ffd4177f07a1e8ab723c53f2e60b83893547d10 to avoid conflicting with the stock Munar Excursion Module, the corresponding patches were not updated accordingly. Specifically [SXT/Patches/ModCompatibility/SXT_TweakScale.cfg](https://github.com/linuxgurugamer/SXTContinued/blob/master/GameData/SXT/Patches/ModCompatibility/SXT_TweakScale.cfg#L86) and [SXT/Patches/ModCompatibility/CLS/CLS_StationsBases.cfg](https://github.com/linuxgurugamer/SXTContinued/blob/master/GameData/SXT/Patches/ModCompatibility/CLS/CLS_StationsBases.cfg#L157) have the problem.

**Impact**
I do not run Connected Living Space, but I run TweakScale and this leads to the infamous double-tweakscale-module issue (which does not break Tweakscale anymore, but still produces an ugly warning when loading a craft in VAB/SPH) and an incorrect default scale for the stock `MEMLander`.

**Fix**
Obvious: replace `MEMLander` with `MEMLanderSXT` in the two files mentioned herebefore.

**Additional information**
The RealPlume config from [KSP-RO/RealPlume-StockConfigs](https://github.com/KSP-RO/RealPlume-StockConfigs) also uses the old name `MEMLander`. Specifically [RealPlume-Stock/SXT Continued/MEMLander.cfg](https://github.com/KSP-RO/RealPlume-StockConfigs/blob/master/GameData/RealPlume-Stock/SXT%20Continued/MEMLander.cfg#L1) has the problem. I will open an issue over there referencing this one. **Edit:** done, see [#83](https://github.com/KSP-RO/RealPlume-StockConfigs/issues/83) in RealPlume StockConfigs.

---

PS: Hi @linuxgurugamer! I run 25 mods managed by you, thanks for all the work 👍

**Comment by linuxgurugamer** [comment]
Fixed in upcoming release
