### ISSUE TITLE
Oscar-C Fuel Tank has black texture

### ISSUE THREAD

**Issue by Ruedii** [linuxgurugamer/SXTContinued#76]
The Oscar-C 0.625m fuel tank has a plain black texture, likely due missing texture asset.

**Comment by linuxgurugamer** [comment]
Thank you, fixing it now

**Comment by linuxgurugamer** [comment]
Can you please identify which version of KSP has this problem?  I've tested on both 1.7.3 and 1.8.1 and it's fine on both

**Comment by Ruedii** [comment]
I will rerun the script pulling depricated textures, maybe the script was updated since I last ran it.

It might also be an interaction with restock.  

Finally, I will test it again in 1.9.1 to make sure I still encounter it.  
I don't use the part because RLA and Restock+ provide similar parts.

**Comment by Ruedii** [comment]
Update: Fixed as of latest SXT Continued Release in 1.9.1  (Not sure when it was fixed; as I said, I haven't paid attention.)

Closing . . .
