### ISSUE TITLE
Update version file for KSP 1.10?

### ISSUE THREAD

**Issue by NathanKell** [linuxgurugamer/SXTContinued#79]
We've been using SXT in 1.10 with no issues (in the RO-verse) for...quite some time, and it would be awesome if the version file could be updated, that way CKAN could find it without having to add 1.8 compat. Bet stock players would like that too. :)

(Might be safe to go past 1.10 as well, not sure; we're still on 1.10.)

**Comment by linuxgurugamer** [comment]
Thanks for the report.
I'll update for 1.11, but 1.12 needs some work (missing textures)

Edit:  Since it pulls from Spacedock, I updated Spacedock's compatibility.  Let me know how it goes, assuming it works, I'll then be able to make the 1.12 update

**Comment by NathanKell** [comment]
Looks good to me! NetKAN picked it up and updated the CKAN meta fine. Cheers! :)
