### ISSUE TITLE
Space shuttle nose cones

### ISSUE THREAD

**Issue by Comwarrior** [linuxgurugamer/SXTContinued#8]
Since 0.23 i have been updating "Space Shuttle Nose Cones" by Kamik up to date with KSP for my own use.
These nosecones have a small amount of monoprop, RCS jets and heat shielding designed to give manoeuvrability in space but also heat shielding for re/entry.

I've been thinking of releasing it but can't get a hold of author to get permission.

**Comment by linuxgurugamer** [comment]
I don't know why.  You've certainly waited long enough, and, according to the thread:
http://forum.kerbalspaceprogram.com/index.php?/topic/93853-0900-ssnc-space-shuttle-rcs-nosecone/
which, BTW, was updated to 0.90, is licensed under GPLv3.
So go ahead and release, you don't need his permission.
