### ISSUE TITLE
Broken textures on certain parts

### ISSUE THREAD

**Issue by ZombieZilla** [linuxgurugamer/SXTContinued#80]
Certain parts seem to have broken textures in KSP 1.12.2, most notably on the Conformal Cone MK3, RCS booms, and Sputnik parts.
I tried on a clean install, using only SXT and its dependencies and the issue is still there.
![sxt](https://user-images.githubusercontent.com/48612811/141458773-ccca6f54-5ec9-40da-b279-be9a4d566a29.png)

Would you be able to take a further look into this? Thanks.

**Comment by linuxgurugamer** [comment]
You didn't read the install instructions.
Instructions are in the README, as well as the OP on the forum
